server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka

  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true


# 微服务_info内容构建
info:
  app.name: leicx-microservicecloud
  company.name: www.leicx.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

zuul:
  #  多个可以用"*"表示
  #  ignored-services: "*"
  ignored-services: microservicecloud-dept
  #  用自定义名称代替真实服务名称
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
  #  前缀：访问路由需要加上该前缀
  prefix: /lcx
